---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: example-mongodb
  namespace: {{ .Values.namespace}}
spec:
  members: {{ .Values.replica_count }}
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ .Values.user_name }}
      db: {{ .Values.db_name }}
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram

